export type ViewState =
    | 'landing' | 'auth' | 'login' | 'signup' | 'diagnostic' | 'tribe_diagnostic'
    | 'catalog' | 'pricing' | 'search' | 'consultant_profile' | 'consultant_marketplace'
    | 'report_view' | 'hr_report' | 'partner_landing' | 'partner_pricing' | 'fix_mode'
    | 'mission_brief' | 'dashboard' | 'consultant_dashboard' | 'partner_dashboard'
    | 'action_lab' | 'second_brain' | 'ai_ad_studio' | 'locker' | 'settings'
    | 'blog_feed' | 'live_schedule' | 'live_session' | 'category' | 'course'
    | 'studio' | 'students' | 'ad_manager' | 'billing' | 'clients' | 'consultant_onboarding'
    | 'company_profile' | 'team' | 'admin_dashboard' | 'admin_verifications' | 'blog_editor'
    | 'diagnostic_result'
    | 'deep_scan_intro' | 'deep_scan_assessment' | 'deep_scan_result';

export type UserRole = 'student' | 'trainer' | 'consultant' | 'enterprise_admin' | 'admin' | 'partner';

export type RegionCode = 'US' | 'GB' | 'FR' | 'UG' | 'KE' | 'NG' | 'IN' | 'GLOBAL';
export type CurrencyCode = 'USD' | 'EUR' | 'GBP' | 'UGX' | 'KES' | 'NGN' | 'INR';
export type LanguageCode = 'en' | 'fr' | 'sw';
export type PricingTier = 1 | 2 | 3;

export interface LocaleProfile {
    country: RegionCode;
    currency: CurrencyCode;
    language: LanguageCode;
    pricingTier: PricingTier;
    contentRegion: string;
    regionGroup: string;
}

export interface PillarScores {
    operations: number;
    money: number;
    market: number;
    leadership: number;
    innovation: number;
    risk: number;
    people: number;
}

export interface DeepScanScores {
    pillars: Record<string, number>; // 0-100
    confidence: Record<string, 'High' | 'Med' | 'Low'>;
}

export interface DeepScanChapter {
    theory: string;
    diagnosis: string;
    psychology: string;
    financials: string;
    prescription: string;
}

// Standard Archetypes
export type Archetype =
    | 'The Sovereign' | 'The Uncrowned King' | 'The Iron General' | 'The Storm Survivor' | 'The Hidden Gem'
    // Produce Aggregation
    | 'sourcing_strength' | 'sourcing_weakness' | 'sourcing_kpis'
    | 'quality_strength' | 'quality_weakness' | 'quality_kpis'
    | 'logistics_strength' | 'logistics_weakness' | 'logistics_kpis'
    | 'sales_strength' | 'sales_weakness' | 'sales_kpis'
    | 'pricing_strength' | 'pricing_weakness' | 'pricing_kpis'
    | 'cash_strength' | 'cash_weakness' | 'cash_kpis'
    | 'inventory_strength' | 'inventory_weakness' | 'inventory_kpis'
    | 'people_strength' | 'people_weakness' | 'people_kpis'
    | 'compliance_strength' | 'compliance_weakness' | 'compliance_kpis'
    | 'pa_hooks'
    // Aquaculture Archetypes
    | 'The Growth Chaser' | 'The Busy Operator' | 'The Market Taker' | 'The Fragile Winner' | 'The Silent Leak' | 'The Control Builder';

export interface LeakIndices {
    timeLeak: number;
    cashLeak: number;
    riskExposure: number;
}

export interface ImpactBand {
    level: 'Low' | 'Medium' | 'High';
    label: string;
    symptom: string;
}

export type PillarId = 'Operations' | 'Money' | 'Market' | 'Leadership' | 'Innovation' | 'Risk' | 'People';


export type AssemblySeverityStatus = 'Stable' | 'Watch' | 'Critical';

export type SignalTag =
    // OPERATIONS (formerly Engine)
    | 'downtime_drain' | 'reactive_maintenance' | 'preventive_maintenance_gap' | 'changeover_black_hole' | 'bottleneck_bounce'
    | 'flow_instability' | 'manual_dependency' | 'no_stop_codes' | 'weak_shift_handover' | 'tooling_slowdown'
    | 'planning_gap' | 'wip_pileup' | 'no_standard_work' | 'quality_built_late' | 'measurement_blindspot'
    // MONEY (formerly Fuel)
    | 'yield_bleed' | 'shrinkage_leak' | 'underweight_giveaway' | 'inventory_blindspot' | 'energy_burn_spiral'
    | 'cashflow_visibility_gap' | 'pricing_margin_blindspot' | 'discounting_leak' | 'zombie_costs' | 'purchase_panic'
    | 'credit_terms_risk' | 'payment_delay_chokehold' | 'costing_gap' | 'supplier_variance_risk' | 'waste_not_costed'
    // MARKET (formerly Voice)
    | 'buyer_power_trap' | 'spec_drift_discount' | 'weak_proof_pack' | 'channel_dependency' | 'low_repeat_orders'
    | 'weak_onboarding' | 'complaint_handling_gap' | 'value_story_gap' | 'order_fulfillment_instability' | 'pricing_positioning_gap'
    // LEADERSHIP (formerly Brain)
    | 'management_by_memory' | 'no_kpi_ownership' | 'panic_scheduling' | 'priority_whiplash' | 'decision_bottleneck'
    | 'no_variance_review' | 'weak_goal_alignment' | 'no_meeting_to_action' | 'hiring_mismatch' | 'no_accountability_loop'
    // INNOVATION & CREATIVITY (formerly Pulse)
    | 'sku_complexity_tax' | 'low_margin_skus' | 'complaint_echo' | 'no_product_testing_rhythm' | 'pack_size_profit_blindspot'
    | 'quality_definition_gap' | 'slow_bug_fix' | 'no_market_feedback_loop'
    // RISK (formerly Shield)
    | 'hygiene_drift' | 'traceability_gap' | 'label_risk' | 'compliance_blocker_risk' | 'data_security_gap'
    | 'contract_gap' | 'insurance_gap' | 'tax_compliance_gap' | 'ip_brand_protection_gap' | 'disaster_recovery_gap'
    // PEOPLE (formerly Tribe)
    | 'hero_operator_dependence' | 'approval_bottleneck' | 'fear_index' | 'blame_culture' | 'training_gap'
    | 'onboarding_gap' | 'role_clarity_gap' | 'low_psych_safety' | 'meeting_theater' | 'cross_function_breakdown'
    // AGRI-INPUT SPECIFIC
    | 'stockout_tax' | 'queue_to_cash_lag' | 'warehouse_blindness' | 'seasonal_rush_chaos' | 'manual_dependency_trap'
    | 'margin_mirage' | 'credit_chokehold' | 'dead_stock_cemetery' | 'silent_shrink' | 'discount_addiction'
    | 'trust_leak' | 'one_channel_fragility' | 'advice_to_sale_gap' | 'repeat_order_drift' | 'reputation_risk_loop'
    | 'management_by_guessing' | 'priority_whiplash' | 'no_owner_syndrome' | 'procurement_panic_buying'
    // FARM MACHINERY & SERVICES TAGS
    | 'market_offer_positioning' | 'pricing_profit_model' | 'service_operations_dispatch'
    | 'fleet_reliability_maintenance' | 'parts_inventory_control' | 'people_safety_compliance'
    | 'finance_working_capital' | 'data_quality_ci'
    // CROP FARMING SPECIFIC
    | 'market_sales_revenue' | 'production_agronomy_yield' | 'post_harvest_loss_control'
    | 'inputs_procurement_cost' | 'finance_cashflow_survival' | 'people_labor_productivity'
    | 'systems_records_data' | 'risk_compliance_resilience'
    // CATTLE SPECIFIC
    | 'market_pricing_power' | 'herd_strategy_genetics' | 'nutrition_feed_system'
    | 'health_welfare_biosecurity' | 'operations_infrastructure' | 'people_daily_execution'
    | 'finance_cash_control' | 'records_data_compliance'
    // LEGACY CROP TAGS (Keep if needed, or deprecate later)
    | 'blind_pricing' | 'reactive_selling' | 'mixed_quality_loss' | 'reactive_planting' | 'late_response_risk'
    | 'panic_buying' | 'cheap_input_trap' | 'labor_idle_waste' | 'schedule_drift' | 'bulk_loss'
    | 'moisture_rot_risk' | 'transport_panic' | 'trust_gap' | 'blind_spend' | 'universal_cuts'
    | 'weather_blindness' | 'memory_management'
    | 'assortment_confusion' | 'bundle_blindspot' | 'seasonal_offer_stagnation'
    | 'counterfeit_exposure' | 'compliance_shock' | 'liability_landmine'
    | 'sales_without_standards' | 'ethics_drift' | 'hero_staff_dependence'
    // FARM MACHINERY & SERVICES TAGS (v2)
    | 'downtime_debt' | 'breakdown_tax' | 'dispatch_chaos' | 'spare_parts_blackhole' | 'route_waste'
    | 'job_card_blindness' | 'peak_season_overload' | 'margin_mirage' | 'fuel_burn_leak' | 'quotation_to_cash_lag'
    | 'deposit_discipline_gap' | 'underpricing_trap' | 'parts_markup_leakage' | 'credit_chokehold' | 'trust_collapse_moment'
    | 'seasonal_demand_miss' | 'service_promise_drift' | 'referral_engine_stall' | 'one_buyer_fragility' | 'management_by_whatsapp'
    | 'hero_owner_syndrome' | 'priority_whiplash' | 'no_owner_problem' | 'offer_stagnation' | 'bundle_blindspot'
    | 'data_driven_upsell_gap' | 'liability_landmine' | 'contract_exposure' | 'warranty_war' | 'compliance_shock'
    | 'operator_drift' | 'accountability_fog' | 'field_team_burnout' | 'culture_of_excuses'
    // NEW V1 PACK TAGS
    | 'inventory_accuracy_gap' | 'receiving_slippage' | 'restock_delay' | 'peak_season_chaos' | 'dispatch_delivery_instability'
    | 'expiry_rotation_gap' | 'returns_damage_blindspot' | 'category_margin_blindspot' | 'cash_recon_gap' | 'payment_terms_risk'
    | 'supplier_terms_weak' | 'pricing_inconsistency' | 'referral_weakness' | 'channel_dependency' | 'complaint_handling_gap'
    | 'value_story_gap' | 'followup_gap' | 'kpi_cadence_gap' | 'training_planning_gap' | 'forecasting_guesswork'
    | 'meeting_no_action' | 'role_clarity_gap' | 'supplier_selection_undisciplined' | 'sku_clutter' | 'bundle_engine_missing'
    | 'slow_mover_attachment' | 'no_testing_rhythm' | 'segment_blindspot' | 'offer_measurement_gap' | 'customer_experience_stagnation'
    | 'expiry_compliance_risk' | 'safe_handling_gap' | 'policy_vagueness' | 'credit_contract_gap' | 'supplier_doc_gap'
    | 'fear_silence' | 'cross_team_friction' | 'service_inconsistency' | 'peak_season_burnout' | 'accountability_soft'
    // PRODUCE AGGREGATION & TRADING TAGS
    | 'shrink_tax' | 'cold_chain_hole' | 'queue_to_rot_lag' | 'sorting_bottleneck' | 'truck_half_empty_syndrome' | 'weight_slip_drift'
    | 'dispatch_chaos' | 'margin_mirage' | 'price_shock_exposure' | 'cash_in_transit_risk' | 'supplier_payment_pressure' | 'hidden_fees_drain'
    | 'working_capital_trap' | 'buyer_power_trap' | 'quality_trust_gap' | 'rejected_load_nightmare' | 'relationship_moat' | 'spec_drift_penalty'
    | 'management_by_whatsapp' | 'no_owner_syndrome' | 'season_blindness' | 'procurement_panic' | 'numbers_free_decisions'
    | 'value_add_blindspot' | 'bundle_opportunity' | 'data_advantage_gap' | 'route_intelligence_missing'
    | 'traceability_gap' | 'contract_exposure' | 'compliance_shock' | 'theft_tamper_risk' | 'contamination_liability'
    | 'handling_damage_culture' | 'incentive_misfire' | 'field_agent_drift' | 'blame_culture'
    // NEW PRODUCE AGGREGATION PATTERNS
    | 'sourcing_strength' | 'sourcing_weakness' | 'sourcing_kpis'
    | 'quality_strength' | 'quality_weakness' | 'quality_kpis' | 'quality_definition_gap' | 'claims_leakage'
    | 'logistics_strength' | 'logistics_weakness' | 'logistics_kpis'
    | 'sales_strength' | 'sales_weakness' | 'sales_kpis'
    | 'pricing_strength' | 'pricing_weakness' | 'pricing_kpis'
    | 'cash_strength' | 'cash_weakness' | 'cash_kpis'
    | 'inventory_strength' | 'inventory_weakness' | 'inventory_kpis'
    | 'people_strength' | 'people_weakness' | 'people_kpis' | 'fraud_control' | 'incentive_misalignment'
    | 'compliance_strength' | 'compliance_weakness' | 'compliance_kpis'
    | 'pa_hooks'
    | 'panic_buying' | 'mixed_quality_loss' | 'no_records' | 'stockout_tax' | 'reactive_selling'
    | 'discounting_leak' | 'cashflow_crunch' | 'credit_chokehold' | 'bad_debt' | 'inventory_blindspot' | 'waste_not_costed' | 'rejection_shock' | 'doc_delay_penalty'
    // EXPORT / CROSS-BORDER TRADER TAGS
    | 'logistics_black_hole' | 'doc_delay_penalty' | 'fx_burn' | 'cash_gap_trap' | 'single_market_risk'
    | 'rejection_shock' | 'compliance_fatigue' | 'reactive_planning' | 'traceability_blindspot' | 'commodity_trap'
    | 'contract_loophole' | 'cargo_loss_exposure' | 'skill_gap_admin' | 'integrity_risk_field' | 'packhouse_bottleneck'
    | 'cold_chain_break' | 'freight_rate_blindness' | 'inventory_vis_gap' | 'packaging_waste_bleed' | 'lab_test_delay'
    | 'arrival_quality_unknown' | 'loading_error' | 'input_quality_var' | 'capacity_planning_gap' | 'claims_leakage'
    | 'cost_per_kg_blind' | 'overhead_bloat' | 'vat_reclaim_delay' | 'investor_relations_weak' | 'payment_term_mismatch'
    | 'profit_concentration_risk' | 'hidden_logistics_costs' | 'brand_invisibility' | 'market_intel_gap' | 'relationship_transactional'
    | 'spec_mismatch' | 'new_biz_stagnation' | 'contract_term_weakness' | 'season_extension_gap' | 'cert_deficiency'
    | 'customer_feedback_loop_missing' | 'reactive_firefighting' | 'vision_gap' | 'data_culture_weak' | 'talent_retention_risk'
    | 'sustainability_lip_service' | 'board_governance_gap' | 'succession_risk' | 'innovation_stagnation' | 'communication_silo'
    | 'tech_aversion' | 'value_add_miss' | 'variety_stagnation' | 'logistics_innovation_gap' | 'packaging_basic'
    | 'data_blindness' | 'energy_waste' | 'waste_valorization_miss' | 'learning_stagnation' | 'contract_enforceability_weak'
    | 'cargo_insurance_gap' | 'regulatory_blindspot' | 'supplier_side_selling' | 'cyber_security_weak' | 'political_risk_exposure'
    | 'reputation_risk' | 'climate_risk_exposure' | 'single_logistic_partner' | 'internal_theft' | 'specialist_skill_gap'
    | 'integrity_issue' | 'labour_shortage_risk' | 'manager_overload' | 'communication_breakdown' | 'safety_culture_weak'
    | 'performance_review_gap' | 'incentive_misalignment' | 'gender_balance_gap' | 'conflict_handling_poor'
    // STATIONERY & BOOKSTORE TAGS
    | 'sku_fog' | 'seasonality_shock' | 'shelf_maze' | 'queue_chaos' | 'dead_book_trap'
    | 'bargain_drift' | 'credit_sink' | 'cash_drawer_drift' | 'hidden_service_leak'
    | 'one_time_buyer_curse' | 'school_contract_miss' | 'whatsapp_blackhole' | 'bundle_blindness'
    | 'kpi_darkness' | 'stale_shelf_syndrome' | 'theft_tax' | 'counterfeit_piracy_landmine'
    | 'dispute_tax' | 'supplier_short_delivery' | 'scriptless_selling' | 'careless_handling'
    // CATTLE FARMING SPECIFIC
    | 'distress_sale_pct' | 'weak_goal_alignment' | 'culling_drift' | 'feed_waste' | 'drought_panic'
    | 'blind_feeding' | 'disease_blindspot' | 'quarantine_gap' | 'mortality_blindness' | 'fertility_gap'
    | 'calf_mortality_risk' | 'future_profit_leak' | 'routine_drift' | 'stress_handling_loss' | 'injury_risk'
    | 'roi_blindspot' | 'cashflow_crunch' | 'panic_selling' | 'data_blindspot' | 'loss_incidents'

    // SHEEP FARMING SPECIFIC
    | 'mineral_gap' | 'lamb_stunting' | 'condition_loss_risk' | 'storage_loss' | 'reactive_health' | 'drug_resistance_risk'
    | 'footrot_risk' | 'parasite_load' | 'lamb_mortality_risk' | 'flystrike_risk' | 'lamb_survival_gap' | 'weaning_drift'
    | 'quality_drift' | 'no_growth_targets' | 'mixed_flock_inefficiency' | 'hygiene_gap' | 'lamb_safety_gap' | 'stress_loss'
    | 'operational_drag' | 'management_by_memory' | 'role_confusion' | 'cost_blindness' | 'vanity_metrics' | 'commingled_cash'
    | 'loss_acceptance' | 'bad_debt' | 'identification_gap' | 'tracking_gap' | 'security_gap' | 'predator_risk'
    | 'selling_blind' | 'single_buyer_risk' | 'weak_negotiation' | 'grade_blindness' | 'seasonality_miss'
    | 'no_flock_plan' | 'uncontrolled_mating' | 'replacement_drift' | 'biosecurity_gap' | 'premature_scale'
    | 'inbreeding_risk' | 'output_blindness' | 'herd_structure_gap' | 'pasture_mismanagement' | 'water_gap'
    | 'no_records' | 'disease_spread_risk' | 'loss_denial' | 'uncontrolled_breeding' | 'late_reaction'
    | 'unproductive_stock' | 'pneumonia_risk' | 'theft_risk' | 'review_gap' | 'record_completeness'
    | 'climate_risk' | 'complacency_risk' | 'financial_blindness'
    // PIG FARMING SPECIFIC
    | 'PRICE_DISCOVERY' | 'SALES_READINESS' | 'MARKET_TIMING' | 'CASH_FLOW_PRESSURE' | 'GRADING_DISCIPLINE'
    | 'PRICE_INTELLIGENCE' | 'BUYER_DEPENDENCY' | 'NEGOTIATION_POWER' | 'SALES_PLANNING' | 'MARGIN_VISIBILITY'
    | 'ASSET_PROTECTION' | 'ANIMAL_WELFARE' | 'QUALITY_CONTROL' | 'LOGISTICS_COST' | 'RELATIONSHIP_BUILDING'
    | 'CAPACITY_PLANNING' | 'CULLING_DISCIPLINE' | 'BREEDING_SCHEDULE' | 'REPLACEMENT_STRATEGY' | 'GENETICS_MANAGEMENT'
    | 'SPACE_MANAGEMENT' | 'FLOW_MANAGEMENT' | 'BIOSECURITY_INTERNAL' | 'PRODUCTION_TARGETS' | 'MARKET_ALIGNMENT'
    | 'PERFORMANCE_RECORDING' | 'FEED_EFFICIENCY' | 'COST_CONTROL' | 'GROWTH_TROUBLESHOOTING' | 'NUTRITION_MANAGEMENT'
    | 'WATER_MANAGEMENT' | 'FEED_TRACKING' | 'WASTE_REDUCTION' | 'GROWTH_MANAGEMENT' | 'FEED_STORAGE'
    | 'PERFORMANCE_METRICS' | 'ENVIRONMENTAL_CONTROL' | 'INVENTORY_PLANNING' | 'UNIT_ECONOMICS' | 'QUARANTINE_PROTOCOL'
    | 'DISEASE_RESPONSE' | 'ACCESS_CONTROL' | 'ISOLATION_PROTOCOL' | 'BATCH_MANAGEMENT' | 'HYGIENE_STANDARD'
    | 'TREATMENT_RECORDS' | 'MEDICATION_ACCURACY' | 'PEST_CONTROL' | 'MORTALITY_MANAGEMENT' | 'DISEASE_LEARNING'
    | 'FARROWING_ATTENTION' | 'PIGLET_CARE' | 'BREEDING_ROUTINE' | 'PREPARATION_DISCIPLINE' | 'MORTALITY_REDUCTION'
    | 'PIGLET_NUTRITION' | 'PERFORMANCE_TRACKING' | 'LITTER_MANAGEMENT' | 'NUTRITION_PLANNING' | 'STRESS_MANAGEMENT'
    | 'ANIMAL_CARE' | 'CULLING_DECISIONS' | 'MAINTENANCE_CULTURE' | 'HOUSING_SUITABILITY' | 'ENVIRONMENTAL_HYGIENE'
    | 'CLIMATE_CONTROL' | 'CAPACITY_DISCIPLINE' | 'STANDARD_PROCEDURES' | 'MAINTENANCE_SPEED' | 'GROUP_MANAGEMENT'
    | 'AIR_QUALITY' | 'ROLE_CLARITY' | 'MANAGEMENT_OVERSIGHT' | 'CASH_PRIORITIZATION' | 'INVENTORY_CONTROL'
    | 'FINANCIAL_GRANULARITY' | 'UNIT_COSTING' | 'LOSS_PREVENTION' | 'FINANCIAL_DISCIPLINE' | 'CREDIT_MANAGEMENT'
    | 'CASH_RESILIENCE' | 'CAPITAL_ALLOCATION' | 'DEBT_STRATEGY' | 'MARKET_SENSITIVITY' | 'GROWTH_REINVESTMENT'
    | 'WASTE_VALORIZATION' | 'REVENUE_DIVERSIFICATION' | 'DATA_INTEGRITY' | 'STRATEGIC_CLARITY' | 'FEED_QUALITY'
    | 'MEDICATION_DISCIPLINE' | 'FINANCIAL_REVIEW' | 'RELIABILITY_GAP' | 'OVERCROWDING' | 'FINANCIAL_BLINDNESS'
    | 'WASTE_MANAGEMENT' | 'PRICE_PERFORMANCE' | 'REPRODUCTIVE_PERFORMANCE' | 'SURVIVAL_RATE' | 'PRODUCTIVITY_INDEX'
    | 'ASSET_UPTIME' | 'PLANNING_GAP' | 'BIOSECURITY_CULTURE' | 'MORTALITY_NORMALIZATION' | 'TIME_EFFICIENCY'
    | 'DATA_BLINDNESS' | 'CHANNEL_DIVERSITY' | 'PROFIT_TRACKING'
    // POULTRY FARMING SPECIFIC
    | 'RELIABILITY_SCORE' | 'SUPPLIER_QUALITY' | 'BROODING_SETUP' | 'EARLY_ACCESS'
    | 'UNIFORMITY_TRACKING' | 'MAINTENANCE_PLAN' | 'CASH_SEPARATION' | 'PLACEMENT_GAPS'
    | 'BIOSECURITY_RISK' | 'FEED_WASTE' | 'WATER_SECURITY' | 'HEAT_STRESS'
    | 'BROODING_ERRORS' | 'UNIFORMITY_LOSS' | 'BIOSECURITY_GAP' | 'ISOLATION_FAILURE'
    | 'VACCINATION_GAP' | 'PROCESS_DEPENDENCY' | 'HANDLING_ERRORS' | 'THEFT_RISK'
    | 'CASH_DRAIN' | 'WASTE_LOSS' | 'MORTALITY_TRACKING' | 'UNIFORMITY_METRIC'
    | 'PRICE_BENCHMARK' | 'PROCESS_ADHERENCE'
    | 'BIOSECURITY_ACCESS' | 'CHANNEL_STRATEGY' | 'MARGIN_FOCUS' | 'VALUE_CAPTURE'
    | 'PRODUCT_GRADING' | 'SALES_TIMING' | 'NET_MARGIN_FOCUS' | 'RELIABILITY'
    | 'DISCOUNT_TRACKING' | 'PACKAGING_STANDARD' | 'PREMIUM_SEGMENTATION' | 'PLANNING_AHEAD'
    | 'GROWTH_STRATEGY' | 'PLACEMENT_CADENCE' | 'SUPPLIER_AUDIT' | 'FLOCK_DATA'
    | 'MODEL_OPTIMIZATION' | 'EFFICIENCY_MINDSET' | 'HEAT_STRESS_RESPONSE' | 'EQUIPMENT_MANAGEMENT'
    | 'NUTRITION_DISCIPLINE' | 'VENTILATION_CONTROL' | 'CLIMATE_RESILIENCE' | 'LIGHTING_PROGRAM'
    | 'WORKFLOW_DESIGN' | 'BIOSECURITY_BARRIER' | 'INTENSIVE_CARE' | 'ANIMAL_OBSERVATION'
    | 'AIR_EXCHANGE' | 'LITTER_QUALITY' | 'ADAPTABILITY' | 'DATA_GRANULARITY'
    | 'EARLY_TRACKING' | 'INTERVENTION' | 'STANDARD_WORK' | 'ISOLATION'
    | 'RECORD_KEEPING' | 'HYGIENE_PROTOCOL' | 'WATER_HYGIENE' | 'WASTE_DISPOSAL'
    | 'CROSS_CONTAMINATION' | 'ROOT_CAUSE_ANALYSIS' | 'CYCLE_BREAK' | 'DATA_DRIVEN_MGMT'
    | 'RECORD_DISCIPLINE' | 'ACCOUNTABILITY' | 'MANAGEMENT_RHYTHM' | 'QUALITY_SOP'
    | 'PREVENTIVE_MAINTENANCE' | 'STOCK_CONTROL' | 'SKILL_BUILDING' | 'COMMUNICATION_FLOW'
    | 'GOAL_ALIGNMENT' | 'INVENTORY_DISCIPLINE' | 'FINANCIAL_HYGIENE' | 'THEFT_PREVENTION'
    | 'OVERHEAD_CONTROL' | 'WASTE_REVENUE' | 'PROCUREMENT'
    | 'BREED_SELECTION' | 'DENSITY_CONTROL' | 'PERFORMANCE_REVIEW' | 'MORTALITY_ACCEPTANCE'
    | 'MORTALITY_ANALYSIS' | 'VACCINATION_COMPLIANCE'
    | 'CHANNEL_MIX' | 'WASTE_CONTROL' | 'WATER_UPTIME' | 'PHASE_FEEDING'
    | 'housing_gap' | 'reinvestment_blindspot' | 'bottleneck_ignore'
    | 'kid_mortality_risk' | 'overstocking_risk' | 'people_drift'
    // DAIRY & MILK COLLECTION SPECIFIC
    | 'SPOILAGE_RISK' | 'TEMP_DISCIPLINE' | 'ADULTERATION_RISK' | 'TESTING_GAP'
    | 'ROUTE_INEFFICIENCY' | 'SOP_GAP' | 'FARMER_CHURN' | 'PRICING_LEAKAGE'
    | 'BUYER_POWER' | 'SHRINK_RATE' | 'MAINTENANCE_DELAY' | 'ROLE_CONFLICT'
    | 'TRACEABILITY_GAP' | 'EARLY_CHILL' | 'GENERATOR_READINESS' | 'INSULATED_TRANSPORT'
    | 'CLEANING_PROTOCOL' | 'VOLUME_FORECAST' | 'PAYMENT_TIMELINESS' | 'COMPLAINT_RESOLUTION'
    | 'REJECT_POLICY' | 'HYGIENE_AUDIT' | 'PREMIUM_CAPTURE' | 'BATCH_TRACEABILITY'
    | 'FUEL_EFFICIENCY' | 'VEHICLE_UPTIME' | 'ROUTE_DENSITY' | 'HANDOVER_GAP'
    | 'TRAINING_GAP' | 'CONTRACT_COMPLIANCE' | 'NET_MARGIN_TRACKING' | 'PAYMENT_AUDIT'
    | 'FRAUD_CONTROL' | 'ASSET_CALIBRATION' | 'COMPLIANCE_AUDIT'
    | 'BLAME_CULTURE' | 'ACCOUNTABILITY_FOG' | 'ONBOARDING_GAP' | 'ROLE_CLARITY' | 'CASH_RESILIENCE' | 'INVENTORY_DISCIPLINE' | 'PRODUCT_GRADING' | 'PREMIUM_SEGMENTATION'
    | 'agent_standards_missing' | 'no_weekly_review'
    | 'verbal_deals' | 'mixed_grades'
    | 'shrink_tax' | 'weight_slip_drift' | 'theft_tamper_risk' | 'spec_drift_penalty' | 'quality_trust_gap'
    | 'handling_damage_culture' | 'queue_to_rot_lag' | 'dispatch_chaos' | 'sorting_bottleneck'
    | 'truck_half_empty_syndrome' | 'hidden_fees_drain' | 'margin_mirage' | 'working_capital_trap'
    | 'supplier_payment_pressure' | 'cold_chain_hole' | 'rejection_rate_high' | 'low_repeat_orders'
    | 'relationship_moat' | 'price_shock_exposure' | 'no_presell_pipeline' | 'cash_in_transit_risk'
    | 'cash_recon_weak' | 'data_advantage_gap' | 'buyer_concentration_high' | 'value_add_blindspot'
    | 'no_subscription_model' | 'traceability_gap' | 'compliance_shock' | 'contract_exposure'
    | 'incentive_misfire' | 'management_by_whatsapp'
    | 'logistics_black_hole' | 'freight_rate_blindness' | 'doc_delay_penalty' | 'compliance_fatigue'
    | 'fx_burn' | 'cash_gap_trap' | 'cold_chain_break' | 'arrival_quality_unknown' | 'single_market_risk'
    | 'relationship_transactional' | 'regulatory_blindspot' | 'contract_loophole' | 'payment_term_mismatch'
    // FORESTRY SPECIFIC TAGS
    | 'strategy_positioning' | 'offer_pricing_power' | 'marketing_demand' | 'sales_conversion'
    | 'operations_delivery' | 'finance_profit_control' | 'people_culture_execution'
    | 'risk_compliance' | 'innovation_systems_data'
    // FISHERIES & AQUACULTURE SPECIFIC
    | 'NO_CYCLE_PLAN' | 'NO_BATCH_RECORDS' | 'DENSITY_GUESSWORK' | 'MIXED_BATCHES' | 'QUARANTINE_SKIPPED'
    | 'NO_ARRIVAL_COUNTS' | 'SUPPLIER_SWITCHING' | 'TRANSPORT_IGNORED' | 'INPUTS_LATE' | 'LATE_GRADING'
    | 'NO_BATCH_IDS' | 'BIOMASS_GUESSWORK' | 'HARVEST_REACTIVE' | 'STATIC_PLAN' | 'MORTALITY_TRACKING_WEAK'
    | 'SUPPLIER_DRIVEN_STOCKING' | 'DENSITY_IGNORED' | 'NO_BACKUP_SUPPLY' | 'HEALTH_ASSUMED' | 'INFORMAL_HANDLING'
    | 'ACCLIMATION_VARIES' | 'FEED_START_IMPROVISED' | 'NO_STOCKING_CHECKLIST' | 'CASHFLOW_IGNORED' | 'WASTE_IGNORED'
    | 'FEEDING_BY_HABIT' | 'OPEN_FEED_STORE' | 'REACTIVE_FEED_CHANGE' | 'LEFTOVERS_IGNORED' | 'OCCASIONAL_WEIGHING'
    | 'RATION_CONSTANT' | 'FEED_LOG_DAILY_ONLY' | 'FEEDING_TIMES_FLEXIBLE' | 'ONE_PELLET_SIZE' | 'BLIND_SUPPLIER_TRUST'
    | 'FEED_STORE_POOR' | 'PESTS_TOLERATED' | 'TRUST_BASED_ACCESS' | 'DUMP_FEEDING' | 'FEED_DURING_LOW_DO'
    | 'FCR_UNKNOWN' | 'DRIFT_IGNORED' | 'FEEDING_MEMORY' | 'SPEED_FEEDING' | 'PRICE_ONLY_SUPPLIER' | 'MIXED_FEED_STOCKS'
    | 'REACTIVE_FEED_BUYING' | 'NO_FEED_COMPLIANCE' | 'REACTIVE_WATER_CHECKS' | 'REACTIVE_MORTALITY_RESPONSE'
    | 'VISITOR_CONVENIENCE' | 'REACTIVE_TREATMENT' | 'MIDDAY_DO_CHECKS' | 'LOGS_IGNORED' | 'AERATION_FIXED'
    | 'GENERATOR_REACTIVE' | 'MORTALITY_LEFT_IN' | 'DISPOSAL_INFORMAL' | 'SHARED_TOOLS' | 'HYGIENE_OPTIONAL'
    | 'BATCH_MIXING' | 'BLIND_TREATMENT' | 'NO_TREATMENT_RECORDS' | 'OUTCOMES_IGNORED' | 'REACTIVE_SLUDGE_MGMT'
    | 'REACTIVE_WATER_CHANGE' | 'FORGOTTEN_OUTBREAKS' | 'SIGNS_MISSED' | 'NORMAL_OPS_SICK' | 'OVERFEEDING_RISK'
    | 'EMERGENCY_HEALTH_SPEND' | 'INFORMAL_VET_ADVICE' | 'VISUAL_SIZE_GUESS' | 'CASH_DRIVEN_HARVEST'
    | 'REACTIVE_GRADING' | 'UNAVOIDABLE_LOSSES' | 'OCCASIONAL_SAMPLING' | 'INFORMAL_WEIGHT_DATA'
    | 'HARVEST_ALL_AT_ONCE' | 'AD_HOC_GRADING' | 'CROWDING_UNCONTROLLED' | 'HANDLING_MORTALITY_IGNORED'
    | 'POOR_NETS' | 'ESCAPES_IGNORED' | 'PREDATORS_TOLERATED' | 'DENSITY_UNCHANGED' | 'SALES_TOTALS_ONLY'
    | 'POOR_GROWTH_ACCEPTED' | 'GRADE_MIX_ASSUMED' | 'HARVEST_EXPERIENCE_BASED' | 'COLD_CHAIN_UNREADY'
    | 'WEATHER_REACTIVE' | 'NO_SIZE_TARGETS' | 'DOWNGRADE_REASONS_IGNORED' | 'SELL_WHEN_READY'
    | 'DELAYED_ICING' | 'RARE_TEMP_RECORDS' | 'PRICE_ACCEPTANCE' | 'MIXED_GRADES_SELLING'
    | 'ICING_WORKLOAD_DEPENDENT' | 'DIRTY_CRATES' | 'WATER_QUALITY_IGNORED' | 'NO_TEMP_LOGS' | 'FIX_ON_FAILURE'
    | 'LAST_MINUTE_ICE' | 'SUN_EXPOSURE' | 'ROUGH_HANDLING' | 'UNTAGGED_LOTS' | 'REJECT_REASONS_ASSUMED'
    | 'CLAIMS_NEGOTIATED' | 'INCONSISTENT_GRADING' | 'INFORMAL_TRAINING' | 'HABIT_BASED_DISPATCH'
    | 'WEIGHT_LOSS_IGNORED' | 'VISUAL_SANITATION' | 'COLD_STORAGE_TRUSTED' | 'CHEAP_PACKAGING'
    | 'EQUAL_PRODUCT_TREATMENT' | 'HANDLING_LOSSES_ACCEPTED' | 'DAY_PRICE_TAKER' | 'SINGLE_BUYER_DEPENDENCY'
    | 'DISCOUNT_NEGOTIATION' | 'VALUE_ADD_DUMP' | 'MIXED_GRADE_SALES' | 'REVENUE_ONLY_TRACKING' | 'ASSUMED_MARGIN'
    | 'BUYER_DEPENDENCY' | 'AD_HOC_CLAIMS' | 'VERBAL_PROOF' | 'SPOT_DEALS' | 'URGENCY_NEGOTIATION'
    | 'PAYMENT_DELAYS_ACCEPTED' | 'ONE_TIME_SALES' | 'EQUAL_BUYER_TREATMENT' | 'RANDOM_PRICING'
    | 'DOWNGRADES_NORMAL' | 'HARVEST_THEN_SELL' | 'LOGISTICS_COST_ACCEPTED' | 'UNCONTROLLED_DISCOUNTS'
    | 'BRAND_AFTERTHOUGHT' | 'CRISIS_CHANNEL_SWITCH' | 'NO_YIELD_TRACKING' | 'WEAK_TRACEABILITY'
    | 'BANK_BALANCE_FEELING' | 'REACTIVE_STOCK_CHECKS' | 'REACTIVE_RECEIVABLES' | 'RELATIONSHIP_BASED_APPROVALS'
    | 'COST_RARELY_CALCULATED' | 'NO_CYCLE_BUDGET' | 'INFORMAL_REVIEW' | 'OVERLAPPING_ROLES' | 'OCCASIONAL_COUNTS'
    | 'VARIANCES_ACCEPTED' | 'MEMORY_TRACKING' | 'FLEXIBLE_CREDIT' | 'HAND_TO_MOUTH' | 'UNAUTHORIZED_PURCHASES'
    | 'TRUST_BASED_PAYMENTS' | 'TOTAL_FUEL_TRACKING' | 'FEED_SHRINK_IGNORED' | 'CLAIMS_NORMALIZED' | 'LATE_TAX'
    | 'IMPULSE_CAPEX' | 'COMPETITOR_PRICING' | 'INFORMAL_INCENTIVES' | 'EXCEPTIONS_IGNORED'
    | 'MONTHLY_FINANCE_REVIEW' | 'BREAKDOWN_MAINTENANCE' | 'ASSUMED_BACKUP' | 'TRUSTED_SOP'
    | 'LAST_MINUTE_COMPLIANCE' | 'NO_MAINTENANCE_CALENDAR' | 'OPTIONAL_CHECKLISTS' | 'BAD_LUCK_DOWNTIME'
    | 'REACTIVE_SPARES' | 'GENERATOR_OUTAGE_ONLY' | 'REACTIVE_INSPECTIONS' | 'REACTIVE_SAFETY' | 'INFORMAL_ROLES'
    | 'ASSUMED_TRAINING' | 'ATTENDANCE_ONLY' | 'REACTIVE_COMPLIANCE' | 'INFORMAL_TRACEABILITY'
    | 'VISUAL_SANITATION_AUDIT' | 'RELATIONSHIP_AUTHORITY' | 'VERBAL_HANDOVER' | 'FORGOTTEN_INCIDENTS'
    | 'INFORMAL_VENDORS' | 'REPLACE_WHEN_DEAD' | 'SHARED_TOOLS_ACROSS_UNITS' | 'CRISIS_MEETINGS'
    // BEEKEEPING SPECIFIC
    | 'silent_colony_collapse' | 'varroa_interest_rate' | 'queen_failure_tax' | 'brood_break_unplanned' | 'treatment_resistance_trap'
    | 'managing_hives_not_colonies' | 'paper_profit_only' | 'inspection_theater' | 'calendar_vs_weather' | 'equipment_bottleneck_tax'
    | 'harvest_panic_mode' | 'sticky_room_chaos' | 'labor_drift' | 'moisture_mistake' | 'one_bad_drum'
    | 'dirty_extraction' | 'residue_risk_roulette' | 'adulteration_suspicion' | 'traceability_gap' | 'wholesale_thinking_retail'
    | 'buyer_vs_customer' | 'price_by_rumor' | 'brand_is_margin' | 'seasonal_cash_crash' | 'honey_funding_habits'
    | 'unknown_profit_per_hive' | 'capex_blindness' | 'feed_burn_rate' | 'leakage_theft_storage' | 'inventory_lies'
    // BEEKEEPING CATEGORY TAGS
    | 'site_forage_strategy' | 'colony_strength_queen_system' | 'seasonal_operations_inspection_discipline'
    | 'biosecurity_pests_disease_control' | 'harvesting_extraction_handling' | 'quality_traceability_compliance'
    | 'sales_pricing_channel_strategy' | 'finance_assets_control_system'
    // INPUT SUPPLIER CATEGORY TAGS
    | 'market_offer_strategy' | 'product_integrity_compliance' | 'sourcing_supplier_control'
    | 'inventory_storage_fulfillment' | 'sales_channels_partner_network' | 'customer_success_stewardship'
    | 'pricing_finance_credit' | 'data_traceability_ci'
    // SMALL RUMINANTS SPECIFIC
    | 'market_readiness' | 'pricing_power' | 'breeding_strategy' | 'genetics_selection' | 'nutrition_planning'
    | 'feed_efficiency' | 'parasite_control' | 'biosecurity_quarantine' | 'maintenance_routine' | 'animal_handling'
    | 'role_clarity' | 'continuous_improvement' | 'financial_discipline' | 'unit_economics' | 'record_keeping'
    | 'data_review' | 'pricing_method' | 'buyer_diversification' | 'market_timing' | 'product_consistency'
    | 'quality_feedback' | 'market_intelligence' | 'sales_planning' | 'cash_cycle' | 'margin_protection'
    | 'value_addition' | 'quality_standards' | 'sales_forecasting' | 'customer_relationship' | 'customer_feedback'
    | 'pricing_strategy' | 'payment_terms' | 'transport_efficiency' | 'seasonal_planning' | 'channel_optimization'
    | 'breeding_control' | 'culling_strategy' | 'genetics_improvement' | 'selection_criteria' | 'birth_records'
    | 'mothering_ability' | 'stock_acquisition' | 'productivity_metric' | 'management_timing' | 'weaning_practice'
    | 'special_care' | 'breeding_readiness' | 'birth_preparation' | 'breed_focus' | 'temperament_selection'
    | 'pregnancy_diagnosis' | 'sustainability' | 'breeding_ratio' | 'age_structure' | 'breeding_objectives'
    | 'grazing_management' | 'supplementation_strategy' | 'mineral_nutrition' | 'feed_grouping' | 'feed_security'
    | 'waste_reduction' | 'water_quality' | 'inventory_management' | 'phase_feeding' | 'condition_scoring'
    | 'grazing_timing' | 'feed_transition' | 'drought_planning' | 'browse_management' | 'feed_storage'
    | 'targeted_nutrition' | 'growth_tracking' | 'stocking_rate' | 'feed_quality' | 'nutrition_mindset'
    | 'quarantine' | 'early_detection' | 'parasite_control_plan' | 'resistance_management' | 'disease_control'
    | 'health_records' | 'vet_usage' | 'hoof_care' | 'hygiene_routine' | 'animal_welfare'
    | 'mortality_investigation' | 'visitor_control' | 'fomite_control' | 'vaccination' | 'age_segregation'
    | 'transport_welfare' | 'treatment_protocol' | 'housing_conditions' | 'climate_management' | 'biosecurity_awareness'
    | 'proactive_maintenance' | 'security_routine' | 'facility_zonation' | 'infrastructure_design' | 'feeding_infrastructure'
    | 'medicine_storage' | 'inventory_count' | 'loss_awareness' | 'predator_control' | 'handling_efficiency'
    | 'equipment_maintenance' | 'transport_safety' | 'cleaning_schedule' | 'spatial_planning' | 'security_measures'
    | 'inventory_records' | 'preventive_maintenance' | 'range_management' | 'tool_control' | 'operational_discipline'
    | 'role_definition' | 'instruction_clarity' | 'training_method' | 'issue_resolution' | 'process_consistency'
    | 'performance_metrics' | 'learning_culture' | 'record_ownership' | 'delegation' | 'communication_rhythm'
    | 'observation_skills' | 'compliance' | 'handling_consistency' | 'purchasing_control' | 'staff_retention'
    | 'prioritization' | 'accountability' | 'capacity_building' | 'discipline_fairness' | 'continuous_training'
    | 'financial_monitoring' | 'loss_visibility' | 'financial_separation' | 'purchasing_strategy' | 'cost_allocation'
    | 'expense_forecasting' | 'cash_planning' | 'loss_valuation' | 'pricing_logic' | 'supplier_selection'
    | 'asset_performance' | 'bill_management' | 'reserves' | 'waste_costing' | 'wealth_definition'
    | 'receivables_management' | 'investment_mentality' | 'budgeting' | 'unit_costing' | 'profit_understanding'
    | 'record_habit' | 'basic_logging' | 'productivity_tracking' | 'treatment_records' | 'herd_demographics'
    | 'group_identification' | 'performance_review' | 'risk_monitoring' | 'feedback_loop' | 'weight_tracking'
    | 'genetic_tracking' | 'mortality_analysis' | 'input_tracking' | 'document_retention' | 'resource_monitoring'
    | 'traceability' | 'regulatory_compliance' | 'trend_analysis' | 'data_driven_action' | 'professional_mindset'
    // STORAGE & WAREHOUSING (COLD CHAIN + SILOS) SPECIFIC
    | 'COST_TO_SERVE' | 'PRICING_LOGIC' | 'SLA_DISCIPLINE' | 'DISPUTE_READINESS' | 'CLIENT_SEGMENTATION'
    | 'RISK_PROFILING' | 'MARGIN_PROTECTION' | 'MARGIN_REVIEW' | 'CLIENT_PROFITABILITY' | 'CONTRACT_STANDARD'
    | 'SERVICE_CONTROL' | 'UNPRICED_COMPLEXITY' | 'VALUE_CAPTURE' | 'CAPACITY_UTILIZATION' | 'MARGIN_FOCUS'
    | 'CLAIMS_PROTOCOL' | 'PEAK_MANAGEMENT' | 'SLOW_MOVER_CONTROL' | 'DWELL_MANAGEMENT' | 'DEMAND_FORECASTING'
    | 'ZONE_PROTECTION' | 'SHRINK_AWARENESS' | 'LIABILITY_CLARITY' | 'HANDOFF_CONTROL' | 'DIFFERENTIATION'
    | 'EVIDENCE_BASED_TRUST' | 'RECEIVING_DISCIPLINE' | 'EVIDENCE_CAPTURE' | 'LOT_CONTROL' | 'TRACEABILITY'
    | 'QUALITY_GATE' | 'QA_VERIFICATION' | 'INBOUND_CONTROL' | 'CONDITION_CHECK' | 'ID_DISCIPLINE'
    | 'SEGREGATION' | 'DATA_DISCIPLINE' | 'DOCUMENT_CONTROL' | 'SECURITY_CHECK' | 'WEIGHT_VERIFICATION'
    | 'RISK_BASED_QA' | 'PRODUCT_HANDLING' | 'RELEASE_GATE' | 'ERROR_TRACKING' | 'CONTINUOUS_IMPROVEMENT'
    | 'INTEGRITY_CONTROL' | 'DOCK_TO_STOCK' | 'THROUGHPUT_TRACKING' | 'EXCEPTION_HANDLING'
    | 'TEMP_MONITORING' | 'ALARM_SYSTEM' | 'DOOR_DISCIPLINE' | 'ENERGY_CONTROL' | 'MOISTURE_CONTROL'
    | 'CONDITION_MONITORING' | 'PEST_MANAGEMENT' | 'PREVENTIVE_CONTROL' | 'ROTATION_DISCIPLINE' | 'FEFO_FIFO'
    | 'COLD_CHAIN_MAINTENANCE' | 'HOT_SPOT_DETECTION' | 'AIRFLOW_MANAGEMENT' | 'EXCURSION_RESPONSE'
    | 'CONTAMINATION_CONTROL' | 'AERATION_DISCIPLINE' | 'GRAIN_MANAGEMENT' | 'FUMIGATION_CONTROL'
    | 'TREATMENT_PROTOCOL' | 'HYGIENE_SCHEDULE' | 'GRAIN_TEMP_TRENDING' | 'SHRINK_TRACKING' | 'LOSS_AWARENESS'
    | 'RISK_BASED_STORAGE' | 'INSPECTION_ROUTINE' | 'VERIFICATION' | 'HUMIDITY_CONTROL'
    | 'INVENTORY_ACCURACY' | 'CYCLE_COUNT' | 'DISPATCH_ACCURACY' | 'DOCK_SCHEDULING' | 'CONGESTION_CONTROL'
    | 'SLOTTING_DISCIPLINE' | 'LAYOUT_OPTIMIZATION' | 'WMS_DISCIPLINE' | 'LOCATION_TRACKING' | 'PICK_ACCURACY'
    | 'TRUCK_TURNAROUND' | 'STAGING_DISCIPLINE' | 'REAL_TIME_RECONCILIATION' | 'FLOW_BALANCING'
    | 'RETURNS_CONTROL' | 'HANDLING_REDUCTION' | 'DAMAGE_PREVENTION' | 'SYSTEM_CHECKS' | 'ERROR_PREVENTION'
    | 'ASSET_DISCIPLINE' | 'SPARE_PARTS_READINESS' | 'CALIBRATION_DISCIPLINE' | 'ENERGY_KPI'
    | 'INCIDENT_LOGGING' | 'SAFETY_CULTURE' | 'DAMAGE_TRACKING' | 'HANDLING_DISCIPLINE' | 'INSURANCE_READINESS'
    | 'PM_TRACKING' | 'CASH_MANAGEMENT' | 'COLLECTION_DISCIPLINE' | 'BACKUP_TESTING' | 'LABOR_CONTROL'
    | 'COST_DISCIPLINE' | 'ENERGY_MANAGEMENT' | 'ENERGY_KPI' | 'SOP_TRAINING' | 'CAPABILITY_BUILD'
    | 'SOP_CONVERSION' | 'COMPLIANCE_ROUTINE' | 'AUDIT_READINESS' | 'KEY_PERSON_RISK' | 'PROCESS_STANDARDIZATION'
    | 'INCIDENT_LEARNING' | 'BILLING_ACCURACY' | 'REVENUE_CAPTURE' | 'PROFIT_GRANULARITY' | 'COST_VISIBILITY'
    | 'STANDARD_PROCEDURES'
    // ARTISANAL MINING TAGS
    | 'shutdown_risk_tax' | 'permission_fog' | 'boundary_chaos' | 'silent_bribe_payroll' | 'conflict_premium'
    | 'paperwork_ambush' | 'social_license_debt' | 'regulator_roulette' | 'community_backlash_curve'
    | 'grade_drift' | 'mixed_lot_penalty' | 'trust_discount' | 'buyer_re_test_trap' | 'spec_ambiguity_tax'
    | 'traceability_breakage' | 'compliance_premium_lost' | 'quality_roulette'
    | 'pipeline_hostage' | 'trust_gap_discount' | 'paperwork_stall' | 'inquiry_bleed' | 'silent_churn' | 'market_access_wall'
    | 'negotiation_bleed' | 'credit_creep' | 'pricing_anxiety' | 'discount_culture' | 're_test_ambush'
    | 'cash_cycle_choke' | 'side_sell_leak' | 'margin_erosion_spiral'
    | 'recovery_bleed' | 'downtime_tax' | 'invisible_loss_stream' | 'tool_failure_spiral' | 'process_chaos'
    | 'production_whiplash' | 'incident_wipeout' | 'yield_roulette'
    | 'cashflow_illusion' | 'money_fog' | 'diesel_creep' | 'small_spend_monster' | 'variance_blindness'
    | 'leak_by_a_thousand_cuts' | 'profitless_volume' | 'receivables_trap' | 'margin_blindness'
    | 'injury_tax' | 'hero_dependency' | 'standardless_work' | 'unsafe_speed_trap' | 'fatigue_drift'
    | 'silent_harm_backlog' | 'turnover_churn' | 'culture_debt'
    // MINING SERVICES TAGS
    | 'prequal_panic' | 'audit_ambush' | 'paper_shield_safety' | 'sanctions_surprise' | 'facilitation_tax'
    | 'subcontractor_shadow_risk' | 'reputation_drag' | 'termination_trigger'
    | 'commodity_trap' | 'scope_creep_tax' | 'value_promise_fog' | 'warranty_bleed' | 'discount_reflex'
    | 'unpriced_complexity' | 'one_off_chaos' | 'marginless_growth'
    | 'tender_chasing_addiction' | 'late_to_bid_syndrome' | 'proposal_graveyard' | 'pipeline_drought'
    | 'unqualified_lead_drain' | 'brand_invisibility_tax'
    | 'unbilled_extras' | 'contract_blindspot' | 'discount_addiction' | 'acceptance_gap' | 'payment_drag' | 'claims_chaos'
    | 'emergency_freight_tax' | 'downtime_penalty' | 'rework_bleed' | 'parts_cannibalization' | 'field_improvisation_cost'
    | 'inventory_fog' | 'mobilization_leakage' | 'handover_failure'
    | 'busy_but_broke' | 'invoice_lag' | 'profit_fog' | 'standby_bleed' | 'unpriced_mobilization' | 'inventory_shrink_shadow'
    | 'procedure_drift' | 'rework_tax' | 'silent_turnover_churn' | 'audit_trigger_event' | 'hse_theater' | 'respect_gap_risk'
    // OIL & GAS SERVICES TAGS
    | 'compliance_roulette' | 'traceability_gap_tax' | 'mobilization_delay_bleed' | 'paper_only_controls' | 'policy_fog' | 'award_risk_discount'
    | 'scope_blur_tax' | 'rate_card_race' | 'unpriced_risk' | 'mobilization_underbill' | 'proofless_premium'
    | 'relationship_only_risk' | 'marketing_noise'
    | 'term_sheet_traps' | 'rate_card_drift'
    | 'simops_friction_cost' | 'utilization_illusion' | 'stockout_chaos' | 'uptime_penalty'
    | 'wip_illusion' | 'unpriced_travel' | 'cash_choke'
    | 'weak_signal_blindness' | 'barrier_decay' | 'ethics_exposure'
    | 'documentation_drag' | 'generic_credibility_tax'
    // F&B GENERAL TAGS
    | 'silent_recall_risk' | 'label_drift' | 'allergen_roulette' | 'traceability_fog' | 'audit_panic_tax'
    | 'sanitation_guesswork' | 'coa_theater' | 'complaint_creep' | 'foreign_body_exposure' | 'customer_trust_discount'
    | 'sku_sprawl' | 'promo_profit_trap' | 'margin_dilution' | 'packaging_bleed' | 'complexity_tax'
    | 'taste_drift_cost' | 'shelf_life_shrink' | 'price_architecture_chaos' | 'innovation_theater' | 'value_engineering_regret'
    | 'forecast_fantasy' | 'promo_whiplash' | 'sell_through_gap' | 'calendar_blindspots' | 'stockout_tax'
    | 'overstock_rot' | 'launch_stumble' | 'demand_noise' | 'service_level_erosion'
    | 'big_customer_squeeze' | 'trade_spend_black_hole' | 'chargeback_creep' | 'returns_normalize'
    | 'price_realization_slip' | 'service_level_penalties' | 'expiry_bounce_back' | 'term_stretch_trap'
    | 'changeover_tax' | 'yield_leakage' | 'scrap_cascade' | 'rework_whirlpool' | 'downtime_drain'
    | 'line_stop_surprises' | 'expiry_rot' | 'dispatch_damage' | 'supplier_variability_tax'
    | 'cogs_fog' | 'variance_blindness' | 'waste_tax' | 'overfill_bleed' | 'discount_drift'
    | 'write_off_creep' | 'inventory_cash_trap' | 'term_stretch_squeeze' | 'profitless_growth'
    | 'shift_to_shift_chaos' | 'training_theater' | 'standards_drift' | 'silent_near_misses' | 'incentive_misfire'
    | 'ci_scatter' | 'supervisor_variability_tax' | 'turnover_drag'
    // BAKERY SPECIFIC TAGS
    | 'rework_risk_loop' | 'cooling_zone_contamination_tax' | 'date_code_slip' | 'metal_detector_theater'
    | 'brown_out_waste' | 'proofing_drift' | 'oven_variance_penalty' | 'crumb_loss_cash_leak'
    | 'packing_jam_drain' | 'staling_rot' | 'energy_leak'
    // BEVERAGE SPECIFIC TAGS
    | 'spoilage_tax' | 'cip_theater' | 'biofilm_creep' | 'filler_zone_exposure' | 'ph_drift_penalty'
    | 'oxygen_pickup_leak' | 'leaker_lottery' | 'silent_shelf_life_shrink' | 'dosing_drift'
    | 'filler_stop_storm' | 'reject_cascade' | 'packaging_scrap_storm' | 'co2_leakage'
    | 'cleaning_downtime_trap' | 'speed_without_stability'
    // SNACKS TAGS
    | 'dry_plant_illusion' | 'wet_creep_tax' | 'seasoning_cross_contact' | 'biofilm_beachhead' | 'foreign_body_surprise'
    | 'browning_drift_penalty' | 'supplier_risk_blind_spot' | 'seasoning_bleed' | 'breakage_tax' | 'fines_giveaway'
    | 'oil_drift_penalty' | 'micro_stop_storm' | 'packaging_leak' | 'moisture_pickup_trap' | 'stale_to_shelf_tax'
    | 'changeover_drag' | 'scrap_normalization'
    // BUTCHERY TAGS
    | 'cold_chain_drift' | 'display_case_spoilage_tax' | 'melt_water_rot' | 'cross_contamination_creep' | 'knife_borne_spread'
    | 'repack_roulette' | 'histamine_blind_spot' | 'rte_zone_breach' | 'silent_discard_spiral' | 'trim_tax'
    | 'overweight_bleed' | 'markdown_spiral' | 'display_case_graveyard' | 'melt_water_loss' | 'rehandling_waste'
    | 'supplier_roulette' | 'workflow_drag' | 'leaker_returns' | 'shrink_normalization'
    | 'label_roulette' | 'rework_spiral' | 'slow_mover_trap' | 'full_counter_illusion' | 'premium_margin_left_behind'
    | 'portion_inconsistency_tax' | 'markdown_addiction' | 'rehandling_drag' | 'cut_too_early_penalty' | 'workflow_friction'
    // TEXTILE TAGS
    | 'quality_drift_tax' | 'hidden_rework_payroll' | 'spec_change_chaos' | 'audit_theater' | 'claim_magnet' | 'traceability_fog'
    | 'chemical_compliance_risk' | 'supplier_failure_subsidy' | 'defect_deja_vu' | 'approval_drag' | 'bom_turbulence'
    | 'late_trim_shutdown' | 'shade_band_surprise' | 'bulk_on_assumption' | 'marker_waste_tax' | 'readiness_debt'
    | 'promise_inflation' | 'capacity_fantasy' | 'last_minute_buyer_panic' | 'chargeback_magnet' | 'single_buyer_trap'
    | 'low_margin_volume_addiction' | 'communication_debt' | 'forecast_mirage' | 'rush_order_tax' | 'reputation_erosion'
    | 'phantom_margin' | 'smv_fantasy' | 'free_change_syndrome' | 'discount_creep' | 'cost_blind_quoting'
    | 'cash_trapped_in_wip' | 'overtime_addiction' | 'variance_blindness' | 'invisible_scrap_bill' | 'margin_evaporation'
    | 'slow_trim_graveyard' | 'dso_choke' | 'overhead_creep' | 'silent_leakage_approvals' | 'profit_lag'
    | 'overtime_culture' | 'skill_bottleneck' | 'supervisor_lottery' | 'turnover_tax' | 'training_debt' | 'safety_theater'
    | 'learning_leakage' | 'culture_drift' | 'improvement_drought' | 'pressure_productivity'
    // FURNITURE TAGS
    | 'warranty_factory' | 'finish_rework_spiral' | 'wood_movement_surprise_tax' | 'fitment_roulette' | 'dust_debt_hazard'
    | 'callback_bleed' | 'spec_drift' | 'hardware_misalignment_churn' | 'compliance_fog' | 'last_day_panic_sanding'
    | 'drawing_drift' | 'site_surprise_rebuild' | 'bom_blind_spot' | 'nesting_waste_tax' | 'revision_chaos'
    | 'job_readiness_debt' | 'hardware_shortfall_stalls' | 'quote_optimism_trap' | 'spec_ambiguity_premium' | 'offcut_graveyard'
    | 'lead_leak' | 'quote_fog' | 'scope_creep_politely_killing_margin' | 'follow_up_gap' | 'discount_drift'
    | 'expectation_mismatch_tax' | 'callback_reputation_bleed' | 'free_design_work_sink' | 'bargain_buyer_trap' | 'handover_confusion'
    | 'busy_but_broke_pricing' /* | 'free_change_syndrome' */ | 'warranty_trap' | 'margin_evaporation_at_sanding' | 'deposit_weakness_penalty'
    | 'scope_creep_tax' /* | 'discount_creep' */ | 'hours_variance_blind_spot' | 'material_cash_lock' | 'quote_optimism'
    | 'wip_swamp' | 'scrap_cascade' | 'tool_downtime_theft' | 'finish_bottleneck_choke' | 'damage_in_transit_tax'
    | 'jigless_variation' | 'rework_second_factory' | 'rush_overtime_burn' | 'dirty_shop_drag' | 'late_stage_surprises'
    | 'cash_locked_in_wood' | 'hardware_stockout_stalls' | 'invisible_shrink' | 'wip_money_pit' | 'profit_blind_quoting'
    | 'slow_moving_inventory_graveyard' | 'overdue_cash_choke' | 'scrap_money_leak' | 'emergency_buying_premium' | 'ghost_margin'
    /* | 'skill_bottleneck' */ | 'search_and_move_tax' | 'sop_drift' /* | 'training_debt' | 'supervisor_lottery' */
    | 'hidden_time_loss' | 'near_miss_silence' | 'quality_variation_tax' /* | 'improvement_drought' */ | 'clutter_drag'
    // METAL TAGS
    | 'rework_factory' | 'weld_roulette' | 'inspection_surprise_tax' | 'cut_quality_chaos' | 'paperwork_panic'
    | 'field_repair_bleed' | 'spec_drift' | 'hot_work_risk_debt' | 'fume_liability_shadow_cost' | 'end_of_line_discovery'
    | 'print_ambiguity_tax' | 'revision_whiplash' | 'nesting_waste' | 'job_readiness_debt' | 'engineering_bottleneck'
    | 'scope_fog' | 'site_surprise_rebuild' | 'unpriced_complexity' | 'tooling_scramble' | 'quote_optimism_trap'
    /* | 'lead_leak' | 'quote_fog' */ | 'scope_creep_tax' | 'discount_drift' | 'late_promise_penalty'
    | 'communication_silence_cost' | 'rush_job_chaos' | 'complaint_driven_workflow' | 'no_proof_selling' | 'one_off_customer_trap'
    /* | 'busy_but_broke_pricing' */ | 'consumable_blind_spot' | 'rework_tax' /* | 'free_change_syndrome' */
    /* | 'deposit_weakness_penalty' | 'margin_evaporation' | 'discount_creep' */ | 'terms_fog' | 'unpriced_risk' | 'warranty_trap'
    /* | 'wip_swamp' */ | 'setup_tax' | 'downtime_theft' /* | 'scrap_cascade' */ | 'grinding_spiral'
    /* | 'rush_overtime_burn' */ | 'bottleneck_choke' | 'delivery_chaos_penalty' /* | 'rework_second_factory' */
    /* | 'search_and_move_tax' */ | 'cash_locked_in_steel' /* | 'wip_money_pit' */ | 'emergency_buying_premium'
    | 'stockout_stall' | 'shrinkage_shadow_loss' | 'paperwork_to_cash_delay' /* | 'ghost_margin' */ | 'scrap_money_leak'
    /* | 'overdue_cash_choke' */ | 'profit_blind_spot'
    /* | 'skill_bottleneck' | 'training_debt' | 'clutter_drag' | 'near_miss_silence' | 'supervisor_lottery' */
    /* | 'fire_risk_drift' | 'quality_variation_tax' | 'improvement_drought' */ | 'culture_by_mood'
    // PLASTICS TAGS
    | 'spec_drift_tax' | 'hold_stock_cemetery' | 'complaint_burn_rate' | 'rework_treadmill' | 'contamination_roulette'
    | 'change_control_debt' | 'audit_panic_cost' | 'traceability_fog' | 'silent_returns_bleed' | 'quality_on_hope_shipping'
    | 'startup_scrap_tax' | 'tribal_settings_drift' | 'wrong_artwork_disaster' | 'unstable_process_churn' | 'tooling_neglect_penalty'
    | 'engineering_fire_brigade' | 'changeover_drag' | 'repeatability_gap' | 'job_pack_holes' | 'process_guessing_cost'
    | 'overpromise_penalty' | 'sample_rejection_spiral' | 'account_churn_bleed' | 'pricing_concession_drift' | 'expedite_addiction'
    | 'approval_chaos' | 'big_customer_dependency' | 'credit_note_leakage' | 'silent_lost_rfqs' | 'service_firefighting_tax'
    | 'resin_swing_ambush' | 'commodity_pricing_trap' | 'tooling_subsidy' | 'change_request_bleed' | 'cashflow_choke'
    | 'changeover_tax' | 'oee_leak' | 'startup_scrap_burn' | 'speed_to_scrap_tradeoff' | 'line_clearance_miss'
    | 'mix_up_writeoff' | 'cash_locked_in_resin' | 'emergency_buy_premium' | 'inventory_fiction' | 'obsolete_sku_graveyard'
    | 'pellet_loss_leak' | 'supplier_drift_cost'
    | 'shift_to_shift_drift' | 'deadline_safety_slip' | 'scrap_culture_tax' | 'energy_bleed' | 'meeting_without_closure'
    // SOAP TAGS
    | 'label_drift_tax' | 'batch_fog' | 'complaint_burn_rate' | 'compliance_scramble_cost' | 'change_control_debt'
    | 'hold_stock_cemetery' | 'silent_instability_bleed' | 'micro_surprise_tax' | 'rework_roulette' | 'trust_erosion_premium'
    | 'formula_drift' | 'operator_recipe_economy' | 'salt_curve_chaos' | 'stability_surprise_tax' | 'substitution_roulette'
    | 'water_quality_blindspot' | 'pump_failure_bleed' | 'batch_correction_cost' | 'claims_credibility_leak'
    | 'promo_profit_illusion' | 'discount_addiction' | 'channel_chaos_cost' | 'stockout_penalty' | 'returns_bleed'
    | 'reputation_drag' | 'claim_backfire_risk' | 'slow_paying_volume_trap' | 'overpromise_hangover' | 'hidden_churn'
    | 'margin_evaporation' | 'packaging_shock_tax' | 'complexity_penalty' | 'short_run_bleed' | 'promo_illusion'
    | 'unpriced_customization' | 'cost_model_blindness' | 'low_margin_volume_trap' | 'profit_per_hour_leak'
    | 'changeover_tax' | 'downtime_theft' | 'sku_chaos_penalty' | 'start_up_waste_burn' | 'line_clearance_miss'
    | 'wip_swamp' | 'speed_to_defect_tradeoff' | 'hidden_labor_creep' | 'capacity_leak'
    | 'cash_locked_in_cartons' | 'stockout_stall' | 'expiry_write_off_tax' | 'inventory_fiction' | 'wip_money_pit'
    | 'slow_mover_graveyard' | 'emergency_buy_premium' | 'supplier_drift_cost' | 'overdue_cash_choke' | 'packaging_bottleneck_curse'
    | 'training_debt' | 'hero_dependency' | 'shift_drift' | 'near_miss_silence' | 'chemical_handling_risk_premium'
    | 'cleanup_before_audit_syndrome' | 'injury_downtime_tax' | 'unowned_actions' | 'improvement_drought' | 'safety_under_pressure_slip'
    // BRICKS TAGS
    | 'strength_lottery' | 'dimension_drift_tax' | 'breakage_burn' | 'hidden_microcrack_bleed' | 'rework_by_discount'
    | 'yard_damage_premium' | 'traceability_fog' | 'spec_mismatch_risk' | 'complaint_churn' | 'quality_at_the_end_trap'
    | 'water_ratio_roulette' | 'cement_creep' | 'moisture_blindness' | 'cure_time_theft' | 'density_drift'
    | 'setting_time_surprises' | 'silent_substitution_risk' | 'strength_swing_tax' | 'edge_crumble_bleed' | 'fuel_energy_spike'
    | 'late_delivery_penalty' | 'breakage_by_route' | 'promise_reality_gap' | 'refund_creep' | 'freight_profit_leak'
    | 'site_rejection_tax' | 'dispute_drag' | 'rush_order_chaos' | 'unprotected_loading_loss'
    | 'cement_energy_shock_tax' | 'unpriced_complexity' | 'small_run_bleed' | 'freight_blindspot' | 'breakage_eats_profit'
    | 'cost_model_fog' | 'volume_trap' | 'price_lag_penalty'
    | 'mold_wear_drift' | 'maintenance_debt' | 'curing_bottleneck_choke' | 'early_move_strength_loss' | 'scrap_spiral'
    | 'spares_panic_premium' | 'hidden_rework_bleed' | 'throughput_illusion'
    | 'stop_start_tax' | 'cement_variability_penalty' | 'pallet_choke' | 'slow_mover_yard' | 'cash_hostage_customers'
    | 'overdue_chokehold' | 'hidden_stockout_cost' | 'rush_freight_burn'
    | 'dust_risk_premium' | 'operator_dependence' | 'waste_blindness'
    // WATER & ICE TAGS
    | 'trust_tax' | 'invisible_contamination_risk' | 'lab_only_safety_illusion' | 'label_drift_penalty' | 'regulatory_scramble_cost'
    | 'ice_as_food_blind_spot' | 'barrier_gap' | 'filter_drift_bleed' | 'post_treatment_backslide' | 'biofilm_tax'
    | 'sanitation_debt' | 'equipment_installed_no_control' | 'hidden_recontamination'
    | 'melt_bleed' | 'dirty_packaging_churn' | 'seal_trust_loss' | 'route_profit_illusion' | 'price_war_spiral' | 'availability_tax'
    | 'energy_squeeze' | 'melt_eats_margin' | 'cash_trap_customers' | 'unit_economics_fog'
    | 'micro_stoppage_tax' | 'leak_rate_burn' | 'biofilm_creep' | 'rework_treadmill'
    | 'packaging_choke' | 'heat_damage_risk' | 'hygiene_under_pressure_slip'
    // CHEMICAL TAGS
    | 'label_drift_penalty' | 'sds_scramble_cost' | 'compliance_fog' | 'traceability_blackout' | 'audit_panic_premium'
    | 'restricted_substance_landmine' | 'refund_as_rca_trap' | 'trust_erosion_tax'
    | 'recipe_drift' | 'qc_at_the_end_trap' | 'silent_substitution_risk' | 'stability_surprise' | 'spec_creep'
    | 'instrument_lie' | 'batch_lottery'
    | 'channel_chaos_tax' | 'promise_reality_gap' | 'credit_fueled_growth_trap' | 'undercut_spiral' | 'distributor_drift'
    | 'churn_by_misuse'
    | 'margin_evaporation' | 'volume_trap' | 'claims_eat_profit' | 'cost_model_fog' | 'price_lag_penalty'
    | 'changeover_bleed' | 'maintenance_debt' | 'hidden_yield_loss' | 'rework_spiral' | 'packaging_defect_burn'
    | 'supplier_drift_penalty' | 'cash_hostage_customers' | 'stop_start_tax'
    | 'spill_bleed' | 'compatibility_landmine' | 'incident_downtime_tax' | 'waste_blindness'
    // CHEMICAL / LIGHT INDUSTRIAL V2 TAGS
    | 'batch_drift_tax' | 'label_risk_debt' | 'silent_giveaway_loss' | 'leak_and_return_bleed' | 'spec_confusion_penalty'
    | 'complaint_discount_spiral' | 'release_rush_regret' | 'operator_process_drift' | 'order_of_addition_chaos' | 'rework_blender'
    | 'cross_contamination_tax' | 'change_control_gap' | 'batch_rescue_cost' | 'channel_trust_leak' | 'document_delay_penalty'
    | 'rush_batch_backlash' | 'return_creep' | 'fulfillment_error_tax' | 'cogs_blindness' | 'utility_drift_tax'
    | 'yield_illusion' | 'silent_rework_cost' | 'promo_profit_leak' | 'volume_trap_sku' | 'changeover_black_hole'
    | 'downtime_drain' | 'wip_swamp' | 'label_mix_up_risk' | 'spill_and_flush_loss' | 'schedule_fiction'
    | 'expiry_write_off_burn' | 'substitution_risk_tax' | 'traceability_gap_cost' | 'deadline_safety_slip'
    | 'sds_blindspot_risk' | 'spill_and_cleanup_burn' | 'waste_creep_tax' | 'training_gap_cost' | 'repeat_incident_rent'
    | 'hero_dependency_risk'
    // FURNITURE TAGS
    | 'quality_drift_tax' | 'finish_redo_bleed' | 'callback_spiral' | 'wood_movement_surprise' | 'hardware_regret_cost'
    | 'trust_erosion_fee' | 'warranty_creep' | 'packaging_damage_burn' | 'spec_confusion_penalty' | 'compliance_scramble_premium'
    | 'drawing_to_floor_drift' | 'cutlist_chaos' | 'scrap_by_mismeasure' | 'joinery_shortcut_debt' | 'finish_contamination_tax'
    | 'scope_creep_creep' | 'onsite_resize_penalty' | 'prototype_pollution'
    | 'overpromise_tax' | 'scope_fog_disputes' | 'rush_build_penalty' | 'delivery_damage_bleed' | 'onsite_fix_trap'
    | 'referral_leak' | 'aftercare_drift'
    | 'quote_illusion' | 'unpriced_complexity' | 'free_change_drain' | 'discount_drift' | 'waste_eats_margin'
    | 'rework_wipes_profit' | 'delivery_subsidy' | 'scope_creep_tax'
    | 'hidden_labor_leak' | 'search_and_carry_tax' | 'offcut_graveyard' | 'rework_factory' | 'bottleneck_choke'
    | 'wip_swamp' | 'changeover_bleed' | 'downtime_theft'
    | 'hardware_choke' | 'inventory_fiction' | 'emergency_buy_premium' | 'silent_substitution_risk' | 'storage_damage_tax'
    | 'supplier_drift_penalty' | 'cash_hostage_customers' | 'compliance_document_scramble'
    | 'deadline_safety_slip' | 'dust_debt' | 'injury_downtime_tax' | 'skill_variance_cost' | 'hero_dependency_risk'
    | 'standards_fade' | 'repeat_problem_rent' | 'cleanup_penalty'
    // ASSEMBLY / OEM TAGS
    | 'inspection_lottery' | 'escape_tax' | 'defect_repeat_rent' | 'quality_gate_theater' | 'customer_confidence_erosion'
    | 'revision_roulette' | 'tribal_wi_drift' | 'npi_turbulence_tax' | 'late_fixture_penalty' | 'engineering_hold_pile_up' | 'process_debt'
    | 'expedite_burn' | 'hot_job_chaos' | 'surprise_penalty' | 'rma_repeat_rent' | 'promise_to_deliver_gap' | 'status_fog'
    | 'nre_giveaway' | 'yield_blindspot' | 'free_rush_fee' | 'eco_absorption_bleed' | 'margin_floor_collapse'
    | 'test_pile_penalty' | 'containment_delay_cost'
    | 'shortage_spiral' | 'expedite_premium_burn' | 'line_stop_penalty'
    | 'esd_drift_risk' | 'latent_failure_tax' | 'repeat_finding_rent' | 'training_gap_bleed' | 'standards_fade_under_rush'
    | 'miswire_tax' | 'termination_drift' | 'label_fog' | 'escape_bleed' | 'rework_treadmill' | 'traceability_blackout' | 'revision_confusion'
    | 'board_layout_chaos' | 'eco_absorption' | 'first_article_skip_fee' | 'hold_pile_up'
    // RETAIL / SUPERMARKET TAGS
    | 'store_hygiene_drift' | 'shelf_price_mismatch' | 'fresh_quality_variance' | 'expired_stock_risk' | 'staff_avoidance'
    | 'cold_chain_break' | 'returns_friction' | 'layout_confusion' | 'cleanliness_unowned' | 'safety_incident_silence'
    | 'feedback_void' | 'assortment_stagnation' | 'slow_mover_accumulation' | 'supplier_driven_range' | 'planogram_chaos'
    | 'category_confusion' | 'new_item_failure' | 'private_label_gap' | 'master_data_mess' | 'price_override_bleed'
    | 'unmeasured_promo_loss' | 'discount_addiction' | 'price_drift' | 'cross_subsidy_blindness' | 'stockout_ghost'
    | 'inventory_trust_gap' | 'overbuying_cash_trap' | 'expiry_write_off_spike' | 'emergency_buying_panic' | 'turnover_blindness'
    | 'shrink_normalization' | 'unscanned_loss' | 'receiving_blindness' | 'waste_reaction' | 'queue_churn'
    | 'sop_drift' | 'cash_variance_tolerance' | 'invoice_blindness' | 'margin_mix_blindness' | 'discount_profit_leak'
    | 'credit_stress' | 'payment_security_gap' | 'hero_dependency' | 'training_shadow_gap' | 'turnover_churn'
    | 'skill_bottleneck' | 'audit_theater' | 'reactive_improvement' | 'planogram_gap' | 'unscanned_item_loss' | 'receiving_error_gap'
    // FMCG WHOLESALE & DISTRIBUTION TAGS
    | 'otif_drift' | 'perfect_order_gap' | 'rebate_fog' | 'short_shipment_churn' | 'aged_stock_handcuff'
    | 'fefo_failure' | 'backorder_trust_tax' | 'picking_error_deduction' | 'route_leakage' | 'warehouse_chaos_shortage'
    | 'credit_discipline_gap' | 'master_data_blindness' | 'cost_to_serve_leak' | 'deduction_blindness' | 'promo_roi_illusion'
    | 'trade_spend_bleed' | 'van_sales_theft' | 'stock_dumping_tax' | 'rep_commission_mismatch' | 'listing_fee_trap'
    | 'damage_rate' | 'leadership_gap' | 'claims_leakage'
    // PHARMACY (MODE A) TAGS
    | 'counseling_gap' | 'privacy_void' | 'intervention_missed' | 'refill_leakage' | 'trust_erosion'
    | 'supplier_reliability_gap' | 'substitution_confusion' | 'quarantine_failure' | 'assortment_bloat' | 'deal_buy_expiry_trap'
    | 'discount_drift_theft' | 'price_override_bleed' | 'claim_rejection_waterfall' | 'denial_loop' | 'basket_ethics_drift'
    | 'expiry_profit_leak' | 'fefo_failure' | 'cold_chain_drift' | 'stock_accuracy_gap' | 'dead_stock_trap'
    | 'dispensing_error_rate' | 'near_miss_silence' | 'lasa_risk' | 'workflow_rush_risk' | 'documentation_void'
    | 'controlled_meds_gap' | 'audit_panic_risk' | 'incident_log_gap' | 'refund_leakage' | 'compliance_fatigue'
    | 'competency_gap' | 'sop_fade' | 'training_debt' | 'action_closure_gap'

    // DRUG SHOP (MODE B) TAGS
    | 'referral_gap' | 'red_flag_miss' | 'boundary_drift' | 'privacy_breach' | 'service_rush_error'
    | 'counterfeit_risk_gap' | 'essential_stockout' | 'cash_trap_slow_movers' | 'pricing_confusion'
    | 'discount_drift_smile' | 'ethical_basket_void' | 'temp_log_gap' | 'fefo_ignore'
    | '3_point_check_fail' | 'lasa_mixup' | 'handover_gap' | 'cash_variance_daily'
    | 'license_scope_risk' | 'returns_fraud_gap' | 'training_shadow_only'
    | 'invoice_mismatch_gap' | 'complaint_loop_gap' | 'cross_training_gap' | 'onboarding_gap' | 'turnover_risk';
